---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 41 # latest is also supported if you want new updates ASAP

stages:
  - name: caps2esc
    from: docker.io/library/fedora
    modules:
      - type: script
        scripts:
          - build-caps2esc.sh

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: copy
    from: caps2esc
    src: /out
    dest: /usr/bin/

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://download.opensuse.org/repositories/shells:fish:beta:4/Fedora_%OS_VERSION%/shells:fish:beta:4.repo
      - https://negativo17.org/repos/fedora-multimedia.repo
      - https://negativo17.org/repos/fedora-rar.repo
      - https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/repo/fedora-%OS_VERSION%/ilyaz-LACT-fedora-%OS_VERSION%.repo
    install:
      - adw-gtk3-theme
      - age
      - bat
      - btop
      - duperemove
      - fd-find
      - ffmpeg
      - ffmpeg-libs
      - ffmpegthumbnailer
      - fish
      - fzf
      - gnome-epub-thumbnailer
      - gnome-monitor-config
      - gnome-shell-extension-gsconnect # gnome-extensions module cannot be used due to hard-coded user locations
      - heif-pixbuf-loader
      - inxi
      - lact
      - libfdk-aac
      - libva-utils
      - nautilus-python
      - nvme-cli
      - openrgb-udev-rules
      - openssl
      - pam-u2f
      - pamu2fcfg
      - pipewire-libs-extra
      - rar
      - ripgrep
      - rmlint
      - rocm-smi
      - smartmontools
      - steam-devices
      - tcpdump
      - tmux
      - traceroute
      - vim
      - wl-clipboard
      - yaml-cpp # interception-tools dependency
      - yubikey-manager
      - zstd
    remove:
      - fdk-aac-free
      - ffmpeg-free
      - firefox
      - firefox-langpacks
      - gnome-classic-session
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-background-logo
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-window-list
      - gnome-system-monitor
      - gnome-tour
      - libavcodec-free
      - libavdevice-free
      - libavfilter-free
      - libavformat-free
      - libavutil-free
      - libpostproc-free
      - libswresample-free
      - libswscale-free
      - totem-video-thumbnailer

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.gnome.Boxes
        - org.gnome.Calculator
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.NautilusPreviewer
        - org.gnome.Papers
        - org.gnome.seahorse.Application
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - app.drey.EarTag
        - ca.desrt.dconf-editor
        - com.calibre_ebook.calibre
        - com.github.iwalton3.jellyfin-mpv-shim
        - com.github.taiko2k.tauonmb
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.heroicgameslauncher.hgl
        - com.jeffser.Alpaca
        - com.jeffser.Alpaca.Plugins.AMD
        - com.mattjakeman.ExtensionManager
        - com.spotify.Client
        - com.usebottles.bottles
        - com.valvesoftware.Steam
        - com.visualstudio.code
        - de.haeckerfelix.Shortwave
        - dev.geopjr.Collision
        - io.github.efogdev.mpris-timer
        - io.github.flattool.Warehouse
        - io.github.seadve.Mousai
        - io.mpv.Mpv
        - md.obsidian.Obsidian
        - me.iepure.devtoolbox
        - net.nokyan.Resources
        - net.rpcs3.RPCS3
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - org.mozilla.firefox
        - org.nickvision.tubeconverter
        - org.qbittorrent.qBittorrent
        - org.ryujinx.Ryujinx
        - org.sabnzbd.sabnzbd
        - page.tesk.Refine

    # Multiple repos inclusion is currently not supported (planned to implement in the future):
    # https://github.com/blue-build/modules/issues/146
  # - type: default-flatpaks
  #   notify: true
  #   system:
  #     repo-url: https://flatpak.nils.moe/repo/appstream/cc.spek.Spek.flatpakref
  #     repo-name: spek-origin
  #     install:
  #       - cc.spek.Spek

  - type: gnome-extensions
    install:
      - Bottom Overview
      - Caffeine
      - Clipboard History
      - Dash to Dock
      - Just Perfection
      - Media Label and Controls (Mpris Label)
      - PaperWM
      - 5470 # Weather O'Clock

  - type: script
    scripts:
      - extensions.sh
      - install.sh
      - tweaks.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - Meslo

  - type: gschema-overrides
    include:
      - zz1-my-defaults.gschema.override

  - type: bling
    install:
      - dconf-update-service # For schemas not supported by the gschema-overrides module

  - type: systemd
    system:
      enabled:
        - caps2esc.service
        - flatpak-update.timer
        - I225-rescan.service
        - lactd.service
        - rpm-ostreed-automatic.timer
        - run-media-david-home.automount
        - suspend@david.service
    user:
      enabled:
        - gnome-monitor-config.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
